version: '3'
services:
  fastapi:
    build: 
      context: ./fastapi
    ports:
      - "8000:8000"

  airflow:
    
    image: airflow:latest
    
    build: 
      context: ./airflow
    
    ports:
      - "8080:8080"
    
    volumes:
      - ./airflow:/opt/airflow
    
    command: airflow standalone
